### ISSUE TITLE
Path error in Teku for Docker

### ISSUE THREAD

**Issue by jschp** [protolambda/mergenet-tutorial#20]
The [command](https://github.com/protolambda/mergenet-tutorial#docker-3) to run Teku from docker contains a typo:

flag:
  --data-path "/testnet/nodes/teku0/beacondata" \

should be:
  --data-path "/testnet/public/nodes/teku0/beacondata" \

**Comment by protolambda** [comment]
It should be `/testnet/nodes/teku0`, but maybe it was off somewhere else. #15 cleaned up a lot of the possible issues, hope that helps.
